### ISSUE TITLE
Make toggle switch attractive to look at

### ISSUE THREAD

**Issue by MichaelZhao21** [acmutd/jury#12]
### Is your feature request related to a problem? Please describe.

The toggle switch is ugly as hell (but it technically works ig)

![image](https://user-images.githubusercontent.com/37679458/231371888-51c4da52-76e9-4692-b8f6-e0026f4257f9.png)

### Describe the solution you'd like

Match the figma design for the toggle switch. It should retain the same functionality; just look better. See the image below. Also add primaryLight to tailwind config as listed below if not already there. The ugly toggle switch was added in #11.

### Additional context

![image](https://user-images.githubusercontent.com/37679458/231372012-290f637c-130e-423d-a481-1b033bf5ec1f.png)

### Colors Used

* Projects text - Light
* Projects background - #CEEAF7 (should be Primary Light; need to add to tailwind config)
* Judges text - White
* Judges background - Primary

**Comment by adityarathod** [comment]
mikey you should replace the toggle with a picture of you because you're pretty attractive to look at
