### ISSUE TITLE
Replace GSL

### ISSUE THREAD

**Issue by MichaelZhao21** [acmutd/jury#16]
### Is your feature request related to a problem? Please describe.

Currently, the GSL library requires us to use `debian:bullseye-slim`.

### Describe the solution you'd like

However, we can use a much smaller base image if we get rid of the GSL library dependency. We are LITERALLY only using it for `rgsl::psi::diagamma::psi`.

**Comment by Spaceface16518** [comment]
For context, the equivalent function in `statsrs` (which is pure rust, would be statically linked, and is already in use for `betaln`) is [`digamma`](https://docs.rs/statrs/latest/statrs/function/gamma/fn.digamma.html).
