### ISSUE TITLE
Add Figma link to README

### ISSUE THREAD

**Issue by MichaelZhao21** [acmutd/jury#20]
### Describe the solution you'd like

https://www.figma.com/file/qwBWs4i7pJMpFbcjMffDZU/Jury-(Gavel-Plus)?node-id=8%3A100&t=egLV7iVmwvNRXef5-1

^ Literally just add this to a reasonable place in the README my branch is too messy and im lazy

**Comment by Ankit6989** [comment]
hey shall i also improve your readme??
