### ISSUE TITLE
Use `rocket_db_pools`

### ISSUE THREAD

**Issue by Spaceface16518** [acmutd/jury#26]
### Is your feature request related to a problem? Please describe.

Using a database behind `State` could bottleneck use.

### Describe the solution you'd like

Instead, use the provided `rocket_db_pools` contrib library. It allows you guard requests with individual connections to the database rather than the connection pool. There is first class support for MongoDB.

### Additional context

https://api.rocket.rs/v0.5-rc/rocket_db_pools/

**Comment by MichaelZhao21** [comment]
Irrelevant
